name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run all
      id: run-all
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: run all
        setup-command: sudo -H pip3 install pytest
        command: pytest
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-ALL_RESULTS: "${{steps.run-all.outputs.result}}"
      with:
        runners: run-all
